swagger: "2.0"
info:
  title: Blog Service
  description: Service to perform CRUD operations using goa
  version: ""
host: localhost:8000
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /:
    get:
      tags:
      - blog
      summary: list blog
      description: List all the blogs
      operationId: blog#list
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/StoredBlogResponse'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogListDbErrorResponseBody'
      schemes:
      - http
    post:
      tags:
      - blog
      summary: create blog
      description: Add a new blog
      operationId: blog#create
      parameters:
      - name: Authorization
        in: header
        description: Access github token
        required: true
        type: string
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogCreateRequestBody'
          required:
          - blog
      responses:
        "201":
          description: Created response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/BlogCreateInvalidTokenResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogCreateDbErrorResponseBody'
      schemes:
      - http
  /{id}:
    get:
      tags:
      - blog
      summary: show blog
      description: Show blog based on the id given
      operationId: blog#show
      parameters:
      - name: id
        in: path
        description: ID of the blog to be fetched
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/BlogShowResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogShowDbErrorResponseBody'
      schemes:
      - http
    delete:
      tags:
      - blog
      summary: remove blog
      description: Delete a blog
      operationId: blog#remove
      parameters:
      - name: id
        in: path
        description: ID of blog to remove
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogRemoveDbErrorResponseBody'
      schemes:
      - http
  /{id}/comments:
    patch:
      tags:
      - blog
      summary: add blog
      description: Add a new comment for a blog
      operationId: blog#add
      parameters:
      - name: id
        in: path
        description: Id of the blog
        required: true
        type: integer
      - name: AddRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/BlogAddRequestBody'
          required:
          - comments
      responses:
        "200":
          description: OK response.
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/BlogAddDbErrorResponseBody'
      schemes:
      - http
  /oauth/redirect:
    post:
      tags:
      - oauth
      summary: oauth oauth
      description: Github authentication to post a new blog
      operationId: oauth#oauth
      parameters:
      - name: OauthRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/OauthOauthRequestBody'
      responses:
        "200":
          description: OK response.
          schema:
            type: string
      schemes:
      - http
  /swagger/swagger.json:
    get:
      tags:
      - swagger
      summary: Download gen/http/openapi.json
      description: JSON document containing the API swagger definition
      operationId: swagger#/swagger/swagger.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /user:
    post:
      tags:
      - user
      summary: create user
      description: Add a new blog
      operationId: user#create
      parameters:
      - name: Authorization
        in: header
        description: Access github token
        required: true
        type: string
      - name: CreateRequestBody
        in: body
        required: true
        schema:
          $ref: '#/definitions/UserCreateRequestBody'
          required:
          - user
      responses:
        "201":
          description: Created response.
        "401":
          description: Unauthorized response.
          schema:
            $ref: '#/definitions/UserCreateInvalidTokenResponseBody'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/UserCreateDbErrorResponseBody'
      schemes:
      - http
  /users:
    get:
      tags:
      - user
      summary: list user
      description: List all the users
      operationId: user#list
      responses:
        "200":
          description: OK response.
          schema:
            type: array
            items:
              $ref: '#/definitions/UserResponse'
        "500":
          description: Internal Server Error response.
          schema:
            $ref: '#/definitions/UserListDbErrorResponseBody'
      schemes:
      - http
definitions:
  BlogAddDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogAddRequestBody:
    title: BlogAddRequestBody
    type: object
    properties:
      comments:
        $ref: '#/definitions/CommentRequestBody'
    example:
      comments:
        comment: Asperiores natus iste eaque iure velit.
        id: 15837338112645027660
    required:
    - comments
  BlogCreateDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: false
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogCreateInvalidTokenResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: User token not valid (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogCreateRequestBody:
    title: BlogCreateRequestBody
    type: object
    properties:
      blog:
        $ref: '#/definitions/BlogRequestBody'
    example:
      blog:
        comments:
        - comment: Asperiores natus iste eaque iure velit.
          id: 15837338112645027660
        - comment: Asperiores natus iste eaque iure velit.
          id: 15837338112645027660
        - comment: Asperiores natus iste eaque iure velit.
          id: 15837338112645027660
        name: Sed et aut voluptatem et voluptas.
    required:
    - blog
  BlogListDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogRemoveDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogRequestBody:
    title: BlogRequestBody
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/CommentRequestBody'
        description: Blog will have multiple comments
        example:
        - comment: Asperiores natus iste eaque iure velit.
          id: 15837338112645027660
        - comment: Asperiores natus iste eaque iure velit.
          id: 15837338112645027660
      name:
        type: string
        description: Name of person
        example: Temporibus quam quis.
    description: A Blog describes a blog retrieved by the storage service.
    example:
      comments:
      - comment: Asperiores natus iste eaque iure velit.
        id: 15837338112645027660
      - comment: Asperiores natus iste eaque iure velit.
        id: 15837338112645027660
      - comment: Asperiores natus iste eaque iure velit.
        id: 15837338112645027660
      - comment: Asperiores natus iste eaque iure velit.
        id: 15837338112645027660
      name: Aspernatur ut.
    required:
    - name
    - comments
  BlogShowDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  BlogShowResponseBody:
    title: 'Mediatype identifier: application/vnd.goa-crud.stored-blog; view=default'
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/StoredCommentResponseBody'
        description: Blog with multiple comments
        example:
        - comment: Voluptatem architecto necessitatibus id dolor quos.
          id: 4105474407472471672
        - comment: Voluptatem architecto necessitatibus id dolor quos.
          id: 4105474407472471672
        - comment: Voluptatem architecto necessitatibus id dolor quos.
          id: 4105474407472471672
        - comment: Voluptatem architecto necessitatibus id dolor quos.
          id: 4105474407472471672
      id:
        type: integer
        description: ID is the unique id of the blog
        example: 14179604368104227843
        format: int64
      name:
        type: string
        description: Name of person
        example: Nam possimus asperiores ut.
    description: ShowResponseBody result type (default view)
    example:
      comments:
      - comment: Voluptatem architecto necessitatibus id dolor quos.
        id: 4105474407472471672
      - comment: Voluptatem architecto necessitatibus id dolor quos.
        id: 4105474407472471672
      - comment: Voluptatem architecto necessitatibus id dolor quos.
        id: 4105474407472471672
      - comment: Voluptatem architecto necessitatibus id dolor quos.
        id: 4105474407472471672
      id: 10311198988496816882
      name: Ad dolorem corporis.
    required:
    - id
    - name
    - comments
  CommentRequestBody:
    title: CommentRequestBody
    type: object
    properties:
      comment:
        type: string
        description: Comment for the blog
        example: Quas nesciunt nisi mollitia.
      id:
        type: integer
        description: ID of a comment
        example: 14535572615046656929
        format: int64
    description: A blog will have multiple comments
    example:
      comment: Ut ex aut non.
      id: 12286622965091573265
    required:
    - comment
  OauthOauthRequestBody:
    title: OauthOauthRequestBody
    type: object
    properties:
      token:
        type: string
        description: Access github token
        example: Consequatur rerum autem.
    example:
      token: Id aut assumenda et.
  StoredBlogResponse:
    title: 'Mediatype identifier: application/vnd.goa-crud.stored-blog; view=default'
    type: object
    properties:
      comments:
        type: array
        items:
          $ref: '#/definitions/StoredCommentResponse'
        description: Blog with multiple comments
        example:
        - comment: Atque minima.
          id: 14042026595247118519
        - comment: Atque minima.
          id: 14042026595247118519
        - comment: Atque minima.
          id: 14042026595247118519
        - comment: Atque minima.
          id: 14042026595247118519
      id:
        type: integer
        description: ID is the unique id of the blog
        example: 14611449245875694492
        format: int64
      name:
        type: string
        description: Name of person
        example: Atque itaque odit.
    description: A Blog describes a blog retrieved by the storage service. (default
      view)
    example:
      comments:
      - comment: Atque minima.
        id: 14042026595247118519
      - comment: Atque minima.
        id: 14042026595247118519
      - comment: Atque minima.
        id: 14042026595247118519
      id: 8745972867205850437
      name: Sed est dolor magni quia veritatis.
    required:
    - id
    - name
    - comments
  StoredCommentResponse:
    title: StoredCommentResponse
    type: object
    properties:
      comment:
        type: string
        description: Comment for the blog
        example: Enim rerum sed.
      id:
        type: integer
        description: ID of a comment
        example: 13461490561757903450
        format: int64
    description: A blog will have multiple comments
    example:
      comment: Saepe voluptas necessitatibus labore nam minus.
      id: 10392268228296868887
    required:
    - id
    - comment
  StoredCommentResponseBody:
    title: StoredCommentResponseBody
    type: object
    properties:
      comment:
        type: string
        description: Comment for the blog
        example: Cumque quia aut explicabo et molestiae.
      id:
        type: integer
        description: ID of a comment
        example: 1929732356760849941
        format: int64
    description: A blog will have multiple comments
    example:
      comment: Beatae cum distinctio atque nihil.
      id: 1306199102508281249
    required:
    - id
    - comment
  UserCreateDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: false
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: true
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserCreateInvalidTokenResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: false
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: User token not valid (default view)
    example:
      fault: false
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserCreateRequestBody:
    title: UserCreateRequestBody
    type: object
    properties:
      user:
        $ref: '#/definitions/UserRequestBody'
    example:
      user:
        age: 2340686031751127884
        class: Minus soluta aut dolorum fuga.
        id: 9607508899083994649
        name: Provident perspiciatis accusamus vel nam.
    required:
    - user
  UserListDbErrorResponseBody:
    title: 'Mediatype identifier: application/vnd.goa.error; view=default'
    type: object
    properties:
      fault:
        type: boolean
        description: Is the error a server-side fault?
        example: false
      id:
        type: string
        description: ID is a unique identifier for this particular occurrence of the
          problem.
        example: 123abc
      message:
        type: string
        description: Message is a human-readable explanation specific to this occurrence
          of the problem.
        example: parameter 'p' must be an integer
      name:
        type: string
        description: Name is the name of this class of errors.
        example: bad_request
      temporary:
        type: boolean
        description: Is the error temporary?
        example: true
      timeout:
        type: boolean
        description: Is the error a timeout?
        example: true
    description: Unable to process db request (default view)
    example:
      fault: true
      id: 123abc
      message: parameter 'p' must be an integer
      name: bad_request
      temporary: false
      timeout: true
    required:
    - name
    - id
    - message
    - temporary
    - timeout
    - fault
  UserRequestBody:
    title: 'Mediatype identifier: application/vnd.goa-crud.stored-user; view=default'
    type: object
    properties:
      age:
        type: integer
        description: Age of user
        example: 14528652831057209867
        format: int64
      class:
        type: string
        description: Class of user
        example: Architecto dolores ad.
      id:
        type: integer
        description: ID is the unique id of the user
        example: 13895089233511992435
        format: int64
      name:
        type: string
        description: Name of user
        example: Consectetur consectetur molestiae.
    description: A User describes a user retrieved by the storage service. (default
      view)
    example:
      age: 2221896610376158327
      class: Fugiat optio et aut libero nesciunt fugiat.
      id: 3122857666741473076
      name: Fugiat laudantium.
    required:
    - name
    - age
    - class
  UserResponse:
    title: 'Mediatype identifier: application/vnd.goa-crud.stored-user; view=default'
    type: object
    properties:
      age:
        type: integer
        description: Age of user
        example: 15239164917393232462
        format: int64
      class:
        type: string
        description: Class of user
        example: Recusandae officiis autem.
      id:
        type: integer
        description: ID is the unique id of the user
        example: 15301857737020518312
        format: int64
      name:
        type: string
        description: Name of user
        example: Officiis sint eos quisquam.
    description: A User describes a user retrieved by the storage service. (default
      view)
    example:
      age: 6469214100147636234
      class: Quisquam vel dolores quis eligendi beatae.
      id: 3016746933722887550
      name: Voluptatum nisi inventore laudantium.
    required:
    - name
    - age
    - class
